---
kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: 192.168.0.64:5000/btwholesaleapi
    registry: 192.168.0.64:5000
    tags: latest
    insecure: true
